export const COMM_CREATE = 'COMM_CREATE';
export const MASSDK_CREATE = 'MASSDK_CREATE';
export const MASSFAZ_CREATE = 'MASSFAZ_CREATE';
export const MASSMODE_CREATE = 'MASSMODE_CREATE';
export const STATSAVE_CREATE = 'STATSAVE_CREATE';
export const MAP_CREATE = 'MAP_CREATE';
export const COORDINATES_CREATE = 'COORDINATES_CREATE';
